### ISSUE TITLE
Display hangs during playback

### ISSUE THREAD

**Issue by comicalman** [lucky01/PIN2DMD#1]
Created just 4 keyframes (frameseqs) and saved my project. 
When I try it during playtesting, the display stops - right at my first replacement frame and requires me to restart the display altogether. 
I did renamed palettes.dat to pin2dmd.pal.  Was there also a naming convention change for pin2dmd.fsq?

see this post for the project files:
http://vpuniverse.com/forums/topic/2268-pin2dmd-editor/page-12#entry29878

**Comment by lucky01** [comment]
Which version of pin2dmd are you running. The zip file in your posting contained a dozen of projects. Please only attach the project your problem is referring to (XML and dump)

**Comment by comicalman** [comment]
I am using pin2dmd v 2.29
See:XFiles_V4m.xml
The 'other' files you refer to are not projects, but rather palettes.  Not sure, but you might need them to see what is going with the project.

**Comment by lucky01** [comment]
I had a look at your project and it seems that it is caused by the pcap file that you use as a dump for your project. Currently only pinmame dumps are fully supported by the editor and the firmware. 
Pcap files can only be used for palette switching not for frame replacement or addcolor. As a workaround use pinmame dumps to generate framesequences (fsq).
