### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ghost** [lucky01/PIN2DMD#17]
According to the license, this is a non-commercial license. However, many dealers offer these displays. My understanding is that this is now accepted as there is a paid licence for the software. Is this correct? In this case, the license for this project should be more open.

**Comment by lucky01** [comment]
Everbody can download the pcb design and produce pin2dmd compatible hardware to sell it commercially without activation.
To sell preactivated devices dealers have the possibility to donate 20 euro per device in batches of minimum 5 devices
directly to one of the chariity organizations we support with the pin2dmd project donations. That way the dealer will receive a tax deductable donation receipt which is equivalent to a invoice. I will generate the keys for free if you send me a copy of the transaction together with the numbers. It is NOT allowed to use private activation keys to sell preactivated devices. The charity organizations dealer donations go to are chosen individually. Please contact us if you want to go that way and we give you the contact details of the charity organization you have to donate to. Because this is a individual exception which needs to be granted through contacting us, there is no need to change the general license.

**Comment by ghost** [comment]
No plans for this, but the license in the repo does not reflect this correctly:
https://github.com/lucky01/PIN2DMD/blob/master/License.md

I recommend to update the license to reflex the current state.

**Comment by lucky01** [comment]
Which license would you recommend ?

**Comment by ghost** [comment]
As your just saying, everybody can use the hardware design, why not using a simple BSD license that basically says "everybody can do everything"? 
If you want it more restricted, CC BY or CC BY-SA might be a better choice.

**Comment by lucky01** [comment]
As the project owner is always allowed to hange the license and make exceptions I prefer to have a more restricted license and make individual exceptions instead of using a open license and having dealers misinterpret it to their advantage.

**Comment by ghost** [comment]
With the current situation the dealer is at a huge risk. They might not be aware of this but as long as they do not have a written statement from you, they risk consequences as they are doing something that's clearly forbidden by the license. This does not fit to your comment "Everbody can download the pcb design and produce pin2dmd compatible hardware to sell it commercially without activation."

**Comment by lucky01** [comment]
That is exactly what I wanted. Maybe I should have said "Everybody who asks for permission to produce our hardware and sell it will get the permission."

**Comment by ghost** [comment]
I still find it a bit strange that everybody gets the permission even though the license explicitly forbids it, but feel free to do it as you like. In my own business I would not sell these with this kind of license (just FYI: I'm running an electronics business, but it has nothing to do with Pinball).

**Comment by vtrucco** [comment]
> That is exactly what I wanted. Maybe I should have said "Everybody who asks for permission to produce our hardware and sell it will get the permission."

I would like to resell those boards. How can I contact you?

**Comment by lucky01** [comment]
> > That is exactly what I wanted. Maybe I should have said "Everybody who asks for permission to produce our hardware and sell it will get the permission."
> 
> I would like to resell those boards. How can I contact you?

Feel free to do so. From my side it is a DIY project. If you have questions about the hardware please look at www.pin2dmd.com or ask your questions here https://vpuniverse.com/forums/topic/4196-ordering-evo-pcbs-at-chinese-manufactures-questions-and-help/  Unfortunatelly I don´t have enough time . 

As a reseller for activation of the devices you can donate directly to one of the charity projects we support with pin2dmd. As an advantage you will receive a donation receipt which you can use as a invoice for you business.
